### ISSUE TITLE
Undefined class in bert_lm.py

### ISSUE THREAD

**Issue by GianlucaDeStefano** [LauJames/PAT#2]
Hi, I have just cloned the repo, and I am trying to run the attack using the command specified in the readme: 
```
python pat_attack.py --target=mini --imitation_model=imitate.v2  --nsp --lamba_1=0.6 --lambda_2=0.1 --num_beams=10 --topk=128 --mode=train
```
However, I soon get the following error: 
```
Traceback (most recent call last):
  File "pat_attack.py", line 27, in <module>
    from bert_ranker.models.bert_lm import BertForLM
  File "bert_ranker/models/bert_lm.py", line 193, in <module>
    class MaskedMultiHeadSelfAttention(MultiHeadSelfAttention):
NameError: name 'MultiHeadSelfAttention' is not defined
```
The cause is the missing implementation of the class MultiHeadSelfAttention. 
This was probably caused by an unfortunate refactoring of the code.
Could you add back the implementation of the class MultiHeadSelfAttention?

**Comment by LauJames** [comment]
Thank you very much for pointing out this bug. 


I have added the relevant modules in the repo. Please update :)


Best wished,
Jiawei Liu
Wuhan University










At 2024-02-05 00:33:32, "Gianluca De Stefano" ***@***.***> wrote:

Hi, I have just cloned the repo, and I am trying to run the attack using the command specified in the readme:

python pat_attack.py --target=mini --imitation_model=imitate.v2  --nsp --lamba_1=0.6 --lambda_2=0.1 --num_beams=10 --topk=128 --mode=train


However, I soon get the following error:

Traceback (most recent call last):
  File "pat_attack.py", line 27, in <module>
    from bert_ranker.models.bert_lm import BertForLM
  File "bert_ranker/models/bert_lm.py", line 193, in <module>
    class MaskedMultiHeadSelfAttention(MultiHeadSelfAttention):
NameError: name 'MultiHeadSelfAttention' is not defined


The cause is the missing implementation of the class MultiHeadSelfAttention.
This was probably caused by an unfortunate refactoring of the code.
Could you add back the implementation of the class MultiHeadSelfAttention?
